/**
 * Interactive setup wizard for OpenCopy.
 *
 * Run with: pnpm setup
 *
 * Walks the user through:
 *   1. Auto-generates AUTH_SECRET + ENCRYPTION_KEY
 *   2. Prompts for DATABASE_URL (Neon / Supabase / self-hosted)
 *   3. Tests the connection + creates the pgvector extension
 *   4. Writes .env (preserving any existing values)
 *   5. Runs `drizzle-kit migrate` against the new database
 *   6. Prints next-steps copy
 */

import "dotenv/config";
import { createInterface } from "node:readline/promises";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import { resolve } from "node:path";
import { Client } from "pg";

/* ----------------------------------------------------------------------------
 * Pretty terminal output (no deps — pure ANSI)
 * -------------------------------------------------------------------------- */

const c = {
  reset: "\x1b[0m",
  dim: "\x1b[2m",
  bold: "\x1b[1m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  orange: "\x1b[38;5;209m",
};

function bold(s: string) {
  return `${c.bold}${s}${c.reset}`;
}
function dim(s: string) {
  return `${c.dim}${s}${c.reset}`;
}
function ok(s: string) {
  return `${c.green}✓${c.reset} ${s}`;
}
function fail(s: string) {
  return `${c.red}✗${c.reset} ${s}`;
}
function warn(s: string) {
  return `${c.yellow}!${c.reset} ${s}`;
}
function step(n: number, total: number, label: string) {
  return `${c.dim}[${n}/${total}]${c.reset} ${bold(label)}`;
}

const BANNER = `
${c.orange}┌─────────────────────────────────────┐
│  OpenCopy setup                     │
│  ${c.dim}Open-source AI copywriter${c.reset}${c.orange}          │
└─────────────────────────────────────┘${c.reset}
`;

/* ----------------------------------------------------------------------------
 * Helpers
 * -------------------------------------------------------------------------- */

const ENV_PATH = resolve(process.cwd(), ".env");
const ENV_EXAMPLE_PATH = resolve(process.cwd(), ".env.example");

function generateSecret(): string {
  return randomBytes(32).toString("base64");
}

function parseEnv(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const lineRaw of text.split(/\r?\n/)) {
    const line = lineRaw.trim();
    if (!line || line.startsWith("#")) continue;
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (!m) continue;
    let value = m[2];
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    map.set(m[1], value);
  }
  return map;
}

function renderEnv(values: Map<string, string>): string {
  const order = [
    "DATABASE_URL",
    "AUTH_SECRET",
    "AUTH_TRUST_HOST",
    "ENCRYPTION_KEY",
    "NEXT_PUBLIC_APP_URL",
    "DEV_AUTH_ENABLED",
    "AUTH_RESEND_KEY",
    "EMAIL_FROM",
  ];
  const seen = new Set<string>();
  const lines: string[] = [];
  lines.push("# Generated by `pnpm setup` — edit anything you want.");
  lines.push("");
  for (const key of order) {
    if (values.has(key)) {
      lines.push(`${key}=${values.get(key)}`);
      seen.add(key);
    }
  }
  // Append any extra keys the user already had set.
  for (const [key, value] of values) {
    if (!seen.has(key)) lines.push(`${key}=${value}`);
  }
  return lines.join("\n") + "\n";
}

async function testConnection(url: string): Promise<{
  ok: boolean;
  message?: string;
  pgvector?: boolean;
}> {
  const client = new Client({
    connectionString: url,
    connectionTimeoutMillis: 8000,
  });
  try {
    await client.connect();
    await client.query("SELECT 1");
  } catch (err) {
    await client.end().catch(() => {});
    return { ok: false, message: (err as Error).message };
  }
  // Try pgvector — many providers have it pre-installed; some need it created.
  let pgvector = false;
  try {
    await client.query("CREATE EXTENSION IF NOT EXISTS vector");
    pgvector = true;
  } catch (err) {
    pgvector = false;
    return {
      ok: true,
      pgvector: false,
      message: `pgvector unavailable: ${(err as Error).message}`,
    };
  }
  await client.end().catch(() => {});
  return { ok: true, pgvector };
}

function maskUrl(url: string): string {
  return url.replace(/\/\/[^:@/]+:([^@/]+)@/, (m, pw) => {
    const masked = "*".repeat(Math.min(pw.length, 8));
    return m.replace(pw, masked);
  });
}

function isValidPgUrl(url: string): boolean {
  return /^postgres(ql)?:\/\/.+/.test(url);
}

function spawnAndWait(
  command: string,
  args: string[],
): Promise<{ code: number }> {
  return new Promise((resolvePromise) => {
    const child = spawn(command, args, {
      stdio: "inherit",
      shell: true,
    });
    child.on("close", (code) => resolvePromise({ code: code ?? 1 }));
  });
}

/* ----------------------------------------------------------------------------
 * Wizard
 * -------------------------------------------------------------------------- */

async function main() {
  process.stdout.write(BANNER);

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string) => rl.question(q);

  // ── Step 1: Existing .env handling ────────────────────────────────────────
  const TOTAL = 5;
  console.log(step(1, TOTAL, "Checking environment"));

  let existing = new Map<string, string>();
  if (existsSync(ENV_PATH)) {
    existing = parseEnv(readFileSync(ENV_PATH, "utf8"));
    console.log(
      `  ${ok(".env exists")} ${dim(`(${existing.size} keys preserved unless overridden)`)}`,
    );
  } else if (existsSync(ENV_EXAMPLE_PATH)) {
    copyFileSync(ENV_EXAMPLE_PATH, ENV_PATH);
    existing = parseEnv(readFileSync(ENV_PATH, "utf8"));
    console.log(`  ${ok("Created .env from .env.example")}`);
  } else {
    console.log(`  ${ok("Starting from scratch")}`);
  }

  // ── Step 2: Secrets ───────────────────────────────────────────────────────
  console.log("\n" + step(2, TOTAL, "Generating secrets"));

  if (
    !existing.get("AUTH_SECRET") ||
    existing.get("AUTH_SECRET")?.startsWith("replace-")
  ) {
    existing.set("AUTH_SECRET", generateSecret());
    console.log(`  ${ok("AUTH_SECRET generated")}`);
  } else {
    console.log(`  ${ok("AUTH_SECRET already set")} ${dim("(kept)")}`);
  }
  if (
    !existing.get("ENCRYPTION_KEY") ||
    existing.get("ENCRYPTION_KEY")?.startsWith("replace-")
  ) {
    existing.set("ENCRYPTION_KEY", generateSecret());
    console.log(`  ${ok("ENCRYPTION_KEY generated")}`);
  } else {
    console.log(`  ${ok("ENCRYPTION_KEY already set")} ${dim("(kept)")}`);
  }
  if (!existing.get("AUTH_TRUST_HOST")) {
    existing.set("AUTH_TRUST_HOST", "true");
  }
  if (!existing.get("NEXT_PUBLIC_APP_URL")) {
    existing.set("NEXT_PUBLIC_APP_URL", "http://localhost:3000");
  }
  if (!existing.get("DEV_AUTH_ENABLED")) {
    existing.set("DEV_AUTH_ENABLED", "true");
  }

  // ── Step 3: DATABASE_URL ──────────────────────────────────────────────────
  console.log("\n" + step(3, TOTAL, "Database connection"));
  console.log(
    dim(
      "  OpenCopy needs Postgres with the pgvector extension.\n" +
        "  Easiest path: " +
        c.reset +
        c.cyan +
        "Neon free tier" +
        c.reset +
        dim(" → https://neon.tech (no credit card)\n") +
        dim("  Supabase free tier works too: https://supabase.com/dashboard/projects\n"),
    ),
  );

  let dbUrl = existing.get("DATABASE_URL") ?? "";
  let dbOk = false;
  let pgvectorOk = false;
  while (!dbOk) {
    if (dbUrl && !dbUrl.includes("placeholder")) {
      const reuse = (
        await ask(
          `  Use existing DATABASE_URL (${maskUrl(dbUrl)})? [Y/n] `,
        )
      )
        .trim()
        .toLowerCase();
      if (reuse === "n" || reuse === "no") {
        dbUrl = "";
      }
    }
    if (!dbUrl) {
      const input = (
        await ask(`  Paste your DATABASE_URL: `)
      ).trim();
      if (!input) {
        console.log(`  ${warn("Skipping — you can edit .env and rerun later.")}`);
        break;
      }
      dbUrl = input;
    }
    if (!isValidPgUrl(dbUrl)) {
      console.log(
        `  ${fail("That doesn't look like a Postgres URL")} ${dim("(should start with postgres:// or postgresql://)")}`,
      );
      dbUrl = "";
      continue;
    }
    process.stdout.write(`  ${dim("Testing connection…")} `);
    const result = await testConnection(dbUrl);
    if (result.ok) {
      console.log(`${ok("connected")}`);
      if (result.pgvector) {
        console.log(`  ${ok("pgvector extension ready")}`);
        pgvectorOk = true;
      } else {
        console.log(
          `  ${warn("pgvector unavailable")} ${dim(`— ${result.message ?? "extension creation failed"}`)}`,
        );
        console.log(
          `  ${dim("  Switch to Neon / Supabase / pgvector image — V1.2+ features need it.")}`,
        );
      }
      dbOk = true;
      existing.set("DATABASE_URL", dbUrl);
    } else {
      console.log(`${fail("failed")}`);
      console.log(`  ${dim(result.message ?? "unknown error")}`);
      const retry = (await ask("  Try again with a different URL? [Y/n] "))
        .trim()
        .toLowerCase();
      if (retry === "n" || retry === "no") break;
      dbUrl = "";
    }
  }

  // ── Step 4: Write .env ───────────────────────────────────────────────────
  console.log("\n" + step(4, TOTAL, "Writing .env"));
  writeFileSync(ENV_PATH, renderEnv(existing));
  console.log(`  ${ok(".env written")} ${dim(`(${ENV_PATH})`)}`);

  // ── Step 5: Migrations ────────────────────────────────────────────────────
  console.log("\n" + step(5, TOTAL, "Running migrations"));
  if (!dbOk) {
    console.log(
      `  ${warn("Skipping — no working DATABASE_URL.")} ${dim("Re-run `pnpm setup` once your DB is reachable.")}`,
    );
  } else if (!pgvectorOk) {
    console.log(
      `  ${warn("Skipping — pgvector extension unavailable.")} ${dim("Without it, migrations will fail.")}`,
    );
  } else {
    rl.close();
    const { code } = await spawnAndWait("pnpm", ["db:migrate"]);
    if (code !== 0) {
      console.log(`\n${fail("Migration failed")} (exit ${code})`);
      console.log(
        dim(
          "  Common causes: pgvector not installed, DATABASE_URL wrong, network issue.\n" +
            "  Re-run `pnpm db:migrate` after fixing.",
        ),
      );
      process.exit(code);
    }
    console.log(`\n  ${ok("Migrations applied")}`);
  }

  rl.close();

  // ── Done ────────────────────────────────────────────────────────────────
  console.log(`
${c.green}${bold("Setup complete!")}${c.reset}

${bold("Next:")}
  ${c.cyan}pnpm dev${c.reset}     ${dim("→ start the dev server on http://localhost:3000")}

${bold("In the app:")}
  1. Sign in — any email, any password ${dim("(≥6 chars; dev provider is on)")}
  2. Settings → AI Providers → paste OpenRouter key ${dim("→ openrouter.ai/keys")}
  3. Settings → AI Providers → Embeddings → paste OpenAI key ${dim("→ platform.openai.com/api-keys")}
  4. Brand voices → New voice → paste samples → Analyze
  5. Agents → Copywriter / Localizer to start running flows

${bold("Self-host (later):")}
  ${c.cyan}docker compose --profile full up${c.reset} ${dim("→ runs the app + Postgres image with pgvector")}
`);
}

main().catch((err) => {
  console.error(`\n${fail("Setup failed")}`);
  console.error(err);
  process.exit(1);
});
